- platform: template
  name: "Projector Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFE01
        command: 0xFF00

- platform: template
  name: "Soundbar Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBE41

- platform: template
  name: "Soundbar Volume Up"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBE41

- platform: template
  name: "Soundbar Volume Down"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBA45

- platform: template
  name: "Soundbar Mute"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xB748

- platform: template
  name: "HDMI Switcher Power"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF30C

- platform: template
  name: "HDMI Switcher Input 1"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFE01

- platform: template
  name: "HDMI Switcher Input 2"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xFC03

- platform: template
  name: "HDMI Switcher Input 3"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF807

- platform: template
  name: "HDMI Switcher Input 4"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF609

- platform: template
  name: "HDMI Switcher Input Cycle"
  on_press:
    - remote_transmitter.transmit_nec:
        address: 0x7F80
        command: 0xF10E
